mappings:
  EcommerceTaskDashboardReset: Sunnysideup\EcommerceDashboard\Tasks\EcommerceTaskDashboardReset
  EcommerceDashboardPanel_FavouriteProducts: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanelFavouriteProducts
  EcommerceDashboardPanel_LatestOrders: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanelLatestOrders
  EcommerceDashboardPanel_OrderStep: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanelOrderStep
  EcommerceDashboardPanel_OrderCount: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanelOrderCount
  EcommerceDashboardPanel_SearchHistory: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanelSearchHistory
  EcommerceDashboardPanel_IncompletePayments: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanelIncompletePayments
  EcommerceDashboardPanel: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanel
  EcommerceDashboard: Sunnysideup\EcommerceDashboard\EcommerceDashboard
