mappings:
  EcommerceTaskDashboardReset: Sunnysideup\EcommerceDashboard\Tasks\EcommerceTaskDashboardReset
  EcommerceDashboardPanel_FavouriteProducts: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanel_FavouriteProducts
  EcommerceDashboardPanel_LatestOrders: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanel_LatestOrders
  EcommerceDashboardPanel_OrderStep: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanel_OrderStep
  EcommerceDashboardPanel_OrderCount: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanel_OrderCount
  EcommerceDashboardPanel_SearchHistory: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanel_SearchHistory
  EcommerceDashboardPanel_IncompletePayments: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanel_IncompletePayments
  EcommerceDashboardPanel: Sunnysideup\EcommerceDashboard\Model\EcommerceDashboardPanel
  EcommerceDashboard: Sunnysideup\EcommerceDashboard\EcommerceDashboard
