---
Name: ecommerce_dashboard
After:
   - 'framework/*'
   - 'cms/*'
   - 'dashboard/*'
   - 'ecommerce/*'
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
   - 'ecommerce_dashboard/css/ecommercedashboard.css'

AdminRootController:
  default_panel: 'CMSMain'


EcommerceRole:
  admin_role_permission_codes:
    - CMS_ACCESS_Dashboard
    - CMS_ACCESS_DashboardAddPanels
    - CMS_ACCESS_DashboardConfigurePanels
    - CMS_ACCESS_DashboardDeletePanels

---
Only:
  moduleexists: 'grouped-cms-menu'
---
SilverStripe\Admin\LeftAndMain:
  menu_groups:
    Shop:
      - EcommerceDashboard
