---
Name: ecommerce_dashboard
After: 'framework/*', 'cms/*', 'dashboard/*'
---
LeftAndMain:
  extra_requirements_css:
   - 'ecommerce_dashboard/css/ecommercedashboard.css'

AdminRootController:
  default_panel: 'CMSMain'


EcommerceRole:
  admin_role_permission_codes:
    - CMS_ACCESS_Dashboard

---
Only:
  moduleexists: 'grouped-cms-menu'
---
LeftAndMain:
  menu_groups:
    Shop:
      - EcommerceDashboard
